language: node_js
node_js:
  - 11
cache: 
  - npm
  - node_modules
before_script:
  - cd TicTacToe-app
  - npm install
script:
  - npm run test
  - npm run lint
  - npm run build:travis

deploy:
  provider: script
  before_script: chmod +x Scripts/docker-deploy.sh 
  script: bash ../Scripts/docker-deploy.sh
  on:
    branch: master