language: node_js
node_js:
 - 11
before_script: 
  - chmod +x docker-deploy.sh
  - cd TicTacToe-app
  - npm install
script: 
  - npm run test
  - npm run lint
  - .././docker-deploy.sh
  - cd ..
  - ./docker-deploy.sh