version: '3'
services:
  run-db:
    image: tictactoe-mssql
    container_name: tictactoe.dev.db
    build:
      context: ./mssql
      dockerfile: DOCKERFILE
    ports:
      - 1433:1433
  run-api:
    image: tictactoe-api
    container_name: tictactoe.dev.api
    build:
      context: ./TicTacToe.API/TicTacToe.WebApi/
      dockerfile: DOCKERFILE
    environment:
        - ASPNETCORE_ENVIRONMENT=docker
    ports:
      - 8080:80
    depends_on:
      - run-db
#    links:
#      - run-db:db
  run-web:
    image: tictactoe-app
    container_name: tictactoe.dev.web
    build: 
      context: ./TicTacToe-app
      dockerfile: Dockerfile
#    ports:
#      - 4200:80
    environment:
      VIRTUAL_HOST: "app.andkra.eu"

      #NETWORK IMPLEMENTIEREN
      # andkra:8080 nur für network sowie mssql nur für network network