version: '3'
services:
  run-db:
    image: tictactoe-mssql
    container_name: tictactoe.dev.db
    build:
      context: ./mssql
      dockerfile: DOCKERFILE
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    expose:
      - "1433"
    volumes:
      - ${MSSQL_VOLUME}
  run-api:
    image: tictactoe-api
    container_name: tictactoe.dev.api
    build:
      context: ./TicTacToe.API/TicTacToe.WebApi/
      dockerfile: DOCKERFILE
    environment:
        ASPNETCORE_ENVIRONMENT: docker
        CUSTOMCONNSTR_DefaultConnection: Server=tictactoe.dev.db,1433;Database=master;User=sa;Password=${DB_PASSWORD};
#        ASPNETCORE_ConnectionStrings__TestConnect: Server=tictactoe.dev.db,1433;Database=master;User=sa;Password=${DB_PASSWORD};
    ports:
      - 8081:80
    depends_on:
      - run-db
#    links:
#      - run-db:db
  run-web:
    image: tictactoe-app
    container_name: tictactoe.dev.web
    build: 
      context: ./TicTacToe-app
      dockerfile: Dockerfile
    ports:
      - 4200:80
    environment:
      VIRTUAL_HOST: "app.andkra.eu"
      VIRTUAL_PORT: 4200
    expose:
      - "4200"
networks:
  default:
    external:
      name: proxynet